language: go

go:
  - "1.15"

services:
  - 'docker'

before_install:
  - make download

jobs:
  include:
    - stage: "Tests"
      name: "Unit Test"
      script:
        - docker-compose up -d database
        - make test
    - stage: "Build Image"
      if: branch = main
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make build-image

notifications:
  email: false