version: '3.8'

services:
  app:
    build: app/
    restart: unless-stopped
    environment:
      APP_DB_USERNAME: postgres
      APP_DB_PASSWORD: postgres
      APP_DB_NAME: productdb
    depends_on:
      - database
    ports:
      - "8010:8010"
    networks:
      - backend

  database:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  postgres:

networks:
  backend: