version: '3.3'

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      APP_DB_USERNAME: $APP_DB_USERNAME
      APP_DB_PASSWORD: $APP_DB_PASSWORD
      APP_DB_NAME: $APP_DB_NAME
      APP_DB_HOST: database
    depends_on:
      - database
    ports:
      - "8010:8010"
    networks:
      - backend

  database:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: $APP_DB_USERNAME
      POSTGRES_PASSWORD: $APP_DB_PASSWORD
      POSTGRES_DB: $APP_DB_NAME
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  postgres:

networks:
  backend: