apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    service: backend
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ammerzon/golang-rest:62f8610
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8010
          env:
            - name: APP_DB_NAME
              value: "productdb"
            - name: APP_DB_USERNAME
              value: "postgres"
            - name: APP_DB_PASSWORD
              value: "postgres"
            - name: APP_DB_HOST
              value: "postgres-postgresql"
---